version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-boost:11.1.0-1.76.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - run:
          name: "Install build dependency: Ishiko/C++ Platform"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/platform.git && cd platform/build/gnumake && make
      - checkout:
          path: /projects/ishiko/cpp/text
      - run:
          name: Build
          command: cd /projects/ishiko/cpp/text/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Errors"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Types"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/types.git && cd types/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Collections"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/collections.git && cd collections/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Process"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/process.git && cd process/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ FileSystem"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/filesystem.git && cd filesystem/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Diff"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/diff.git && cd diff/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Tests"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/tests.git && cd tests/core/build/gnumake && make
      - run:
          name: Test build
          command: cd /projects/ishiko/cpp/text/tests/build/gnumake && make
      - run:
          name: Run the tests
          command: cd /projects/ishiko/cpp/text/tests/build/gnumake && ./IshikoTextTests
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
